/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Expomovil;

import javax.swing.DefaultListModel;

/**
 *
 * @author allanvz
 */
public class ConsultarVehiculo extends javax.swing.JFrame {
    
    DefaultListModel listaColoresS;
    DefaultListModel listaExtrasS;

    /**
     * Creates new form ConsultarVehiculo
     */
    public ConsultarVehiculo(Vehiculo vehiculo) {
        initComponents();
        this.listaColoresS = new DefaultListModel();
        this.listaColor.setModel(listaColoresS);
        this.listaExtrasS = new DefaultListModel();
        this.listaExtras.setModel(listaExtrasS);
        this.labelAgencia.setText(vehiculo.getAgencia().getNombre());
        this.labelCantidad.setText(Integer.toString(vehiculo.getCantidad()));
        this.labelCilindrada.setText(Integer.toString(vehiculo.getCilindrada()));
        this.labelCombustible.setText(vehiculo.getCombustible());
        this.labelDescripcion.setText(vehiculo.getDescripcion());
        this.labelMarca.setText(vehiculo.getMarca());
        this.labelModelo.setText(vehiculo.getModelo());
        this.labelPrecio.setText(Double.toString(vehiculo.getPrecio()));
        this.labelTipo.setText(vehiculo.getTipo());
        this.labelTransmision.setText(vehiculo.getTransmision());
        agregarExtras(vehiculo.getExtras());
        agregarColores(vehiculo.getColores());
    }
    
    public void agregarExtras(String[] extras) {
        this.listaExtrasS.clear();
        for(int x = 0; x != extras.length; x++) {
            this.listaExtrasS.addElement(extras[x]);
        }
    }
    
    public void agregarColores(String[] colores) {
        this.listaColoresS.clear();
        for(int x = 0; x != colores.length; x++) {
            this.listaColoresS.addElement(colores[x]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaVehiculo = new javax.swing.JPanel();
        panelFoto = new javax.swing.JPanel();
        labelMarca = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaColor = new javax.swing.JList<>();
        labelModelo = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelDescripcion = new javax.swing.JLabel();
        labelCilindrada = new javax.swing.JLabel();
        labelCombustible = new javax.swing.JLabel();
        labelTransmision = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaExtras = new javax.swing.JList<>();
        labelPrecio = new javax.swing.JLabel();
        cerrarVentana = new javax.swing.JButton();
        labelAgencia = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelMarca.setText("jLabel1");

        jScrollPane1.setViewportView(listaColor);

        labelModelo.setText("jLabel2");

        labelTipo.setText("jLabel3");

        labelDescripcion.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        labelCilindrada.setText("jLabel5");

        labelCombustible.setText("jLabel6");

        labelTransmision.setText("jLabel7");

        jScrollPane2.setViewportView(listaExtras);

        labelPrecio.setText("jLabel8");

        cerrarVentana.setText("Close");
        cerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarVentanaActionPerformed(evt);
            }
        });

        labelAgencia.setText("jLabel1");

        labelCantidad.setText("jLabel1");

        javax.swing.GroupLayout VentanaVehiculoLayout = new javax.swing.GroupLayout(VentanaVehiculo);
        VentanaVehiculo.setLayout(VentanaVehiculoLayout);
        VentanaVehiculoLayout.setHorizontalGroup(
            VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                        .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                                .addComponent(labelMarca)
                                .addGap(18, 18, 18)
                                .addComponent(labelModelo)
                                .addGap(18, 18, 18)
                                .addComponent(labelTipo)))
                        .addGap(18, 18, 18)
                        .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                        .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                                .addComponent(labelAgencia)
                                .addGap(81, 81, 81)
                                .addComponent(labelCantidad))
                            .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                                .addComponent(labelCilindrada)
                                .addGap(18, 18, 18)
                                .addComponent(labelCombustible)
                                .addGap(18, 18, 18)
                                .addComponent(labelTransmision)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarVentana)
                        .addGap(98, 98, 98)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaVehiculoLayout.setVerticalGroup(
            VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca)
                    .addComponent(labelModelo)
                    .addComponent(labelTipo)
                    .addComponent(labelPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VentanaVehiculoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCilindrada)
                    .addComponent(labelCombustible)
                    .addComponent(labelTransmision))
                .addGap(7, 7, 7)
                .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarVentana)
                    .addGroup(VentanaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAgencia)
                        .addComponent(labelCantidad)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarVentanaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarVentanaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VentanaVehiculo;
    private javax.swing.JButton cerrarVentana;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAgencia;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCilindrada;
    private javax.swing.JLabel labelCombustible;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTransmision;
    private javax.swing.JList<String> listaColor;
    private javax.swing.JList<String> listaExtras;
    private javax.swing.JPanel panelFoto;
    // End of variables declaration//GEN-END:variables
}
